# Generated by Django 4.2 on 2025-12-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
