# Generated by Codex on 2025-01-01
from django.db import migrations, models


def add_debts_column(apps, schema_editor):
    model = apps.get_model("finanzapp", "MonthlyBudget")
    table = model._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        columns = [
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table
            )
        ]
    if "debts" in columns:
        return
    field = model._meta.get_field("debts")
    schema_editor.add_field(model, field)


class Migration(migrations.Migration):
    dependencies = [
        ("finanzapp", "0002_alter_user_options"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="monthlybudget",
                    name="debts",
                    field=models.FloatField(default=0),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_debts_column, migrations.RunPython.noop),
            ],
        ),
    ]
