# Generated by Codex on 2025-01-01
from django.db import migrations, models


def add_savings_goal_column(apps, schema_editor):
    model = apps.get_model("finanzapp", "MonthlyBudget")
    table = model._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        columns = [
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table
            )
        ]
    if "savings_goal" in columns:
        return
    field = model._meta.get_field("savings_goal")
    schema_editor.add_field(model, field)


class Migration(migrations.Migration):
    dependencies = [
        ("finanzapp", "0003_add_monthlybudget_debts"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="monthlybudget",
                    name="savings_goal",
                    field=models.FloatField(default=0),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_savings_goal_column, migrations.RunPython.noop),
            ],
        ),
    ]
